# Generated by Django 4.1 on 2022-10-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_id_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
