# Generated by Django 4.1 on 2022-10-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_variation_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='product',
        ),
    ]
